### ISSUE TITLE
Error al instalar en Ubuntu con pip

### ISSUE THREAD

**Issue by juanrodriguezmonti** [gosella/autopython#3]
Hola! Al intentar instalar la aplicación usando pip, falla con SyntaxError.  En la siguiente versión de Ubuntu:

root@beq:/home/juan/Descargas# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 15.10
Release:        15.10
Codename:       wily

Todo el traceback, a continuación:

root@beq:/home/juan/Descargas# pip install autopython
Downloading/unpacking autopython
  Downloading autopython-0.3.tar.gz
  Running setup.py (path:/tmp/pip-build-j65f4M/autopython/setup.py) egg_info for package autopython
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip-build-j65f4M/autopython/setup.py", line 3, in <module>
        import autopython
      File "autopython/**init**.py", line 1, in <module>
        from .core import Presenter, **version**
      File "autopython/core.py", line 209
        print(timestamp, message, file=self.logger)
                                      ^
    SyntaxError: invalid syntax
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip-build-j65f4M/autopython/setup.py", line 3, in <module>

```
import autopython
```

  File "autopython/**init**.py", line 1, in <module>

```
from .core import Presenter, __version__
```

  File "autopython/core.py", line 209

```
print(timestamp, message, file=self.logger)

                              ^
```

SyntaxError: invalid syntax

---

Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-j65f4M/autopython
Storing debug log for failure in /root/.pip/pip.log

**Comment by gosella** [comment]
Quizás vaya a sugerir algo tonto pero autopython **sólo funciona en Python 3**.
¿`pip` en Ubuntu 15.10 hace referencia a `pip2` o `pip3`? 
Por el error en la función `print()` me da que pensar que está usando el `pip` de Python 2.7.

Podes forzar instalarlo con Python 3.x haciendo:

`$ pip3 install autopython`

**Comment by gosella** [comment]
También podés instalar la última versión (que aún no tiene release oficial por falta de ganas^H^H^H^H^H tiempo para escribir la documentación) descargando el código desde la rama `ipython` (https://github.com/gosella/autopython/tree/ipython) y ejecutando:

`[autopython] $ python3 setup.py install`

**Comment by juanrodriguezmonti** [comment]
Si, el problema es que es un verdadero dolor de cabeza gestionar múltiples versiones en Ubuntu con pip. Incluso, no existe el paquete de python3 para pip.

(dadalus)root@localhost:/home/juan# pip --version
pip 1.0 from /usr/lib/python2.7/dist-packages (python 2.7)

Aún teniendo Python 3.2 instalado. No existe pip3 en Ubuntu, hay que hacerlo a mano, y ni siquiera estan los paquetes.
Por supuesto que esto no es un problema de autopython, pero - por experiencia te digo - este tipo de situaciones te "alejan" usuarios de la aplicación si es que usan Ubuntu.

Habria que dar algunas instrucciones especiales para Ubuntu, quizás! :)

**Comment by gosella** [comment]
Tantos años de Arch me han acostumbrado a que Python es Python 3.x por defecto... ;-)

No tengo un Ubuntu a mano para confirmar pero http://packages.ubuntu.com/wily/python3-pip dice que pip existe para Python 3, ¿puede ser? ¿Y qué versión de Python 3 trae Ubuntu 15.10? Porque en el sitio anterior figura la 3.4.3. ¿es así?

**En teoría**, si primero ejecutás:

`$ apt install python3-pip python3-colorama python3-pygments`

deberías tener todas las dependencias listas para luego hacer:

`$ pip3 install autopython`

Reconozco que la documentación de AutoPython no es de lo mejorcito... :-(

Si podés, confirmame si funcionó con los pasos anteriores.

Lo ideal sería empaquetarlo para Debian/Ubuntu pero hace muuuucho que no armo un DEB.

Igualmente, estaría bueno si podés instalar el código de la rama ipython (como mencionaba en https://github.com/gosella/autopython/issues/3#issuecomment-228578559). El código es mucho más robusto y refinado. Y tenés además `autoipython` y opcionalmente `autopython` con IPython como shell interactivo :-)

Debería hacer que AutoPython sea un poquito más amigable con Python 2.x (aunque no lo llegue a soportar directamente). Actualmente hace de cuenta que no existe...

**Comment by juanrodriguezmonti** [comment]
Claro, en realidad, corrijo un error mio del principio, esto me pasó en Ubuntu 15 en el desktop, pero también en Ubuntu 12.04 en mi laptop ( chromebook ). Y para 12.04, no existe ese paquete. Con lo cual no hay una forma "simple" de hacer dicha instalación.

Para Ubuntu en versiones más nuevas, con esa solución funciona. He instalado otros paquetes py3 así con pip allí.

Ese seria el problema, la incompatibilidad o dificultad para versiones viejas de Ubuntu. Y, obviamente, que no es una dificultad de Autopython. Es algo relacionado a Ubuntu en dichas versiones, que ya se usan poco, con lo cual no deberíamos prestarle mucha atención.

Sí seria interesante ser más friendly con la 15, que sí se sigue usando. Ver la manera de que no solo tire un error, quizás agregar en la doc algunos detalles sobre cómo proceder. Después mando un pequeño texto para agregar en alguna parte y simplificarle la vida a usuarios no tan expertos que quieran usar autopython.

**Comment by juanrodriguezmonti** [comment]
Vos sabes que actualice Ubuntu, hasta la version 15.04, en donde esta disponible el paquete python3-pip y python-pip, para cada version de Python.

Pude hacer la instalacion con : pip3 install autopython . Antes instale pygments. Funciona todo perfecto en la instalacion.

Como sugerencia, corrijo el issue inicial porque no es un error, sino que falla porque necesita obligatoriamente un archivo a presentar. Caso contrario muestra: 

(dadalus)juan@localhost:/usr/local/bin$ autopython 
Traceback (most recent call last):
  File "/usr/local/bin/autopython", line 5, in <module>
    presenter = Presenter(sys.argv[1], colors=True, animation=True, logging=True)
IndexError: list index out of range

Seria bueno que salga un gentil mensaje de error del tipo "Debe ingresar un archivo para hacer la presentacion" :) O al menos, la ayuda del programa.

**Comment by gosella** [comment]
Es que la UX de la versión 0.3 es nula... Para que funcione, tenés que darle un archivo .py como parámetro:

`(dadalus)juan@localhost:/usr/local/bin$ autopython /home/juan/prueba.py`

Quiero terminar un par de cositas antes de hacer un nuevo release (que estará próximo a la 1.0!) pero mientras podés probar el nuevo código: https://github.com/gosella/autopython/archive/ipython.zip

Deberías poder instalarlo con: 

`$ sudo python3 setup.py install`

Y, _la primicia_: El mismo código **debería andar tanto con Python 2.x como 3.x** :-D

Si en cambio hacés:

`$ sudo python2 setup.py install`

debería funcionar con Python 2.x.

Por ahora `bin/autopython` y `bin/autoipython` están hardcoded para usar python3 en el shebang de los scripts pero sentite en liberdad de adaptarlos según tus necesidades. Pienso hacer que se generen `autopython2` o `autopython3` según corresponda (pero aún no vi como...).

**Comment by juanrodriguezmonti** [comment]
Genial que sea amigable con Python 2, por lo antes descripto. En especial usuarios no muy experimentados y con distribuciones no tan nuevas.

Lo otro, responde claramente a eso que decis. Despues con indicar lo que se necesita para funcionar, sobra, con evitar esa excepcion.

Es genial este proyecto, voy a ver como puedo colaborar.

Juan

**Comment by gosella** [comment]
Juan, si tenés ganas de "beta-testear" un rato, probá si podés instalar correctamente autopython con:

`$ pip install https://github.com/gosella/autopython/archive/v0.7-b1.tar.gz`
(para Python 2.x)

o con:

`$ pip3 install https://github.com/gosella/autopython/archive/v0.7-b1.tar.gz`
(para Python 3.x)

Si no tenés instalados `python-colorama` y `python-pygments` (o sus correspondientes versiones para python3), podés forzar instalarlas como dependencias con pip haciendo:

`$ pip install https://github.com/gosella/autopython/archive/v0.7-b1.tar.gz#egg=autopython[highlighting]`

Son opcionales y si no los tenés instalados (y no los instalas con `[highlighting]`), autopython funciona igualmente excepto que no hace resaltado de sintaxis.

En este punto creería que sólo queda revisar la documentación antes de hacer el release definitivo.

Gracias de antemano!

**Comment by juanrodriguezmonti** [comment]
Ahí va el output. Funcionan perfecto ambos! :+1: 

root@beq:/home/juan# pip install https://github.com/gosella/autopython/archive/v0.7-b1.tar.gz
Downloading/unpacking https://github.com/gosella/autopython/archive/v0.7-b1.tar.gz
  Downloading v0.7-b1.tar.gz (unknown size): 31kB downloaded
  Running setup.py (path:/tmp/pip-xN9uOw-build/setup.py) egg_info for package from https://github.com/gosella/autopython/archive/v0.7-b1.tar.gz

Installing collected packages: autopython
  Running setup.py install for autopython

```
Installing autopython2 script to /usr/local/bin
Installing autoipython2 script to /usr/local/bin
```

Successfully installed autopython
Cleaning up...
root@beq:/home/juan# pip3 install https://github.com/gosella/autopython/archive/v0.7-b1.tar.gz
Downloading/unpacking https://github.com/gosella/autopython/archive/v0.7-b1.tar.gz
  Downloading v0.7-b1.tar.gz
  Running setup.py (path:/tmp/pip-wb0rkxof-build/setup.py) egg_info for package from https://github.com/gosella/autopython/archive/v0.7-b1.tar.gz

Installing collected packages: autopython
  Running setup.py install for autopython

```
Installing autopython3 script to /usr/local/bin
Installing autoipython3 script to /usr/local/bin
```

Successfully installed autopython
Cleaning up...

Sí, por supuesto, que antes habia instalado colorama y pygments.

Gracias a vos! Hasta que este proyecto no llegue a PyCon no paramos ;)
